SandraOrozco/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

authUrl='django.contrib.auth.urls'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SandraOrozcoApp.urls')),
    path('',include('informacion.urls')),
    path('citas/', include('citas.urls')),
    path('contactanos/',include('contactanos.urls')),
    path('inventario/',include('pedidos.urls'),name="inventario"),
    path('caja/',include('cajaMenor.urls')),
    path('agenda/',include('agenda.urls')),
    path('accounts/', include(authUrl)),
    path('accounts/logout/',include(authUrl),name='logout'),
    path('accounts/password_change/',include(authUrl),name='password_change'),
    path('accounts/password_change/done/',include(authUrl),name='password_change_done'),
    path('accounts/password_reset/',include(authUrl),name='password_reset'),
    path('accounts/password_reset/done/',include(authUrl), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',include(authUrl),name='password_reset_confirm'),
    path('accounts/reset/done/',include(authUrl), name='password_reset_complete'),
    path('accounts/login/',include(authUrl),name='login'),
]

agenda/urls.py
from agenda.views import Agenda
from django.contrib.auth.decorators import login_required
from django.urls import path

urlpatterns=[
    path('',login_required(Agenda.as_view()),name="agenda"),
]

citas/urls.py
from django.urls import path
from .views import Vista

urlpatterns=[
    path('',Vista.as_view(),name="citas"),
]

agenda/models.py
from django.db import models

# Create your models here.

agenda/forms.py
from django import forms

horas=[("7:00","7:00"),("7:15","7:15"),("7:30","7:30"),("7:45","7:45"),("8:00","8:00"),("8:15","8:15"),("8:30","8:30"),("8:45","8:45"),("9:00","9:00")
,("9:15","9:15"),("9:30","9:30"),("9:45","9:45"),("10:00","10:00"),("10:15","10:15"),("10:30","10:30"),("10:45","10:45"),("11:00","11:00")
,("11:15","11:15"),("11:30","11:30"),("11:45","11:45"),("12:00","12:00"),("12:15","12:15"),("12:30","12:30"),("12:45","12:45"),("13:00","13:00")
,("13:15","13:15"),("13:30","13:30"),("13:45","13:45"),("14:00","14:00"),("14:15","14:15"),("14:30","14:30"),("14:45","14:45"),("15:00","15:00")
,("15:15","15:15"),("15:30","15:30"),("15:45","15:45"),("16:00","16:00"),("16:15","16:15"),("16:30","16:30"),("16:45","16:45")]

class FormularioEvento(forms.Form):
    
    nombre=forms.CharField(label="Nombre paciente",required=True, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    fecha=forms.CharField(label="Fecha",required=True)
    hora=forms.ChoiceField(label="Hora",choices=horas)
    precio=forms.CharField(label='Precio',required=True,widget=forms.TextInput(attrs={'placeholder': 'Precio'}))
    celular=forms.CharField(label="Celular",required=True,widget=forms.TextInput(attrs={'placeholder': 'Celular'}))
    email=forms.EmailField(label="Email contacto",required=True,widget=forms.TextInput(attrs={'placeholder': 'Email'}))

    

agenda/views.py
from django.db import models
from django.shortcuts import render
from django.views.generic import ListView,FormView,TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from citas.models import Evento
from .forms import FormularioEvento

# Create your views here.


class Agenda(FormView,TemplateView,LoginRequiredMixin):
    template_name='agenda/calendario.html'
    models = Evento
    form_class=FormularioEvento
    login_url ='accounts/login/'

    def get(self,request,*args,**kwargs):
        form = self.form_class()
        eventos = Evento.objects.all()
        return render(request, self.template_name, {'form':form,'object_list':eventos})

    def post(self,request,*args, **kwargs):
        mensaje=''
        error=False
        form = self.form_class(request.POST)
        if form.is_valid():
            n=request.POST.get("nombre")
            f=request.POST.get("fecha")
            h=request.POST.get("hora")
            e=request.POST.get("email")
            c=request.POST.get('celular')
            p=request.POST.get('precio')

            eventos = self.models.objects.filter(start=f)
            ward = True
            for evento in eventos:
                if evento.horaInicio == h:
                    ward =False
            evento = self.models.objects.filter(nombre=n,email=e)
            if evento :
                evento[0].precio=p
                evento[0].save()
            else:
                if ward:
                    self.models.objects.create(nombre=n,start=f,horaInicio=h,email=e,celular=c,precio=p)
                    mensaje= 'Registro exitoso'
                    
                else:
                    error = True
                    mensaje='La hora %s no esta disponible en la fecha %s' %(h,f)
        form = self.form_class()
        eventos=Evento.objects.all()
        return render(request, self.template_name, {'form':form,'mensaje':mensaje,'error':error,'object_list':eventos})

agenda/templates/agenda/calendario.html
{% extends "SandraOrozcoApp/base.html" %}
{% load static %}
{% block extra_css %}
  <link rel="stylesheet" href="{% static 'SandraOrozcoApp/lib/main.css' %}"/>
{% endblock extra_css %}
{% block content %}
{% if mensaje %}
  {% if error %}
    <div class="alert alert-danger">
        <li id="mensaje" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ mensaje }}</li>
    </div>      
  {% else %}
    <div class="alert alert-success">
      <li id="mensaje" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ mensaje }}</li>
    </div>   
  {% endif %}
  
{% endif %}
  <div title="detalle" class="modal fade" id="modal-event" tabindex="-1" role="dialog" aria-labelledby="modal-eventLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="event-title">Detalle de la cita</h5>
            
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
          <form action="" method="POST">
              {% csrf_token %}
              <table>
                    {{ form.as_table }}
              </table>
              <input type="submit" id="agregar" value="Guardar"class="btn btn-secondary"></input>
          </form>
        </div>
        <div class="modal-footer">

        </div>
        </div>
    </div>
    </div>
  <div title="agregarevento" class="modal fade" id="eventoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="modal-title">Agregar Evento</h5>
          </div>
          <div class="modal-body">
            
            <form action="" method="POST">
                {% csrf_token %}
                <table>
                      {{ form.as_table }}
                </table>
                <input type="submit" id="agregar" value="Guardar"class="btn btn-secondary"></input>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div id='calendar'></div>
{% endblock content %}

{% block extra_js %} 
  <script src="{% static 'SandraOrozcoApp/lib/main.js' %}"></script>
  <script>

    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
      var calendar = new FullCalendar.Calendar(calendarEl, {
        
        headerToolbar:{
          rigth: 'prev,next',
          center: 'title',
          left: 'dayGridMonth,dayGridWeek,dayGridDay'
        },
        dateClick: function(info) {
            $('#eventoModal').modal('toggle');
            $('#eventoModal #id_fecha').val(info.dateStr);
            
        },
        eventClick: function(info){
            $('#id_nombre').val(info.event.extendedProps.nombre)
            $('#id_fecha').val(info.event.extendedProps.fecha)
            $('#id_precio').val(info.event.extendedProps.precio)
            $('#id_celular').val(info.event.extendedProps.celular)
            $('#id_email').val(info.event.extendedProps.descripcion)
            $('#id_hora').val(info.event.extendedProps.hora)
            $('#modal-event').modal('toggle');
        },
        events: [
          {% for evento in object_list %}
              {
                title: "{{ evento.horaInicio }} {{ evento.nombre }}",
                start:"{{ evento.start|date:'Y-m-d' }}",
                end: "{{ evento.end|date:'Y-m-d' }}",
                descripcion: "{{ evento.email }}",
                celular: "{{ evento.celular }}",
                precio: "{{ evento.precio }}",
                fecha: "{{ evento.start|date:'Y-m-d' }}",
                nombre:"{{ evento.nombre }}",
                hora:"{{ evento.horaInicio }}",
              },
          {% endfor %}
        ]
      });
      calendar.render();
    });
</script>
{% endblock extra_js %}